[package]
name = "new-coe"
version = "0.1.0"
authors = ["fabru-FHD <fabian.bruenger002@stud.fh-dortmund.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
